//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnotations_PartialViews.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public marca()
        {
            this.modelos = new HashSet<modelo>();
        }
    
        public int id_marca { get; set; }

        [Display(Name = "Nombre de la marca")]
        [Required(ErrorMessage = "Campo requerido")]
        [MinLength(4, ErrorMessage = "El campo debe tener al menos una longitud de 4 caracteres")]
        [MaxLength(30, ErrorMessage = "El campo debe tener como máximo una longitud de 30 caracteres")]
        public string marca1 { get; set; }

        [Display(Name = "País")]
        [Required(ErrorMessage = "Campo requerido")]
        [MinLength(4, ErrorMessage = "El campo debe tener al menos una longitud de 4 caracteres")]
        [MaxLength(30, ErrorMessage = "El campo debe tener como máximo una longitud de 30 caracteres")]
        public string pais { get; set; }
        public string imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modelo> modelos { get; set; }
        public object ErrorMessage { get; internal set; }
    }
}
