//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnotations_PartialViews.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class modelo
    {
        static int anio = DateTime.Now.Year;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modelo()
        {
            this.repuestos = new HashSet<repuesto>();
        }

        public int id_modelos { get; set; }

        [Display(Name = "Nombre del modelo")]
        [Required(ErrorMessage = "Campo requerido")]
        [MinLength(4, ErrorMessage = "El campo debe tener al menos una longitud de 4 caracteres")]
        [MaxLength(30, ErrorMessage = "El campo debe tener como máximo una longitud de 30 caracteres")]
        public string modelo1 { get; set; }

        [Display(Name = "Número de asientos")]
        [Required(ErrorMessage = "Campo requerido")]
        [Range(1, 8, ErrorMessage = "Debe ingresar un número de asientos válido")]
        public Nullable<int> asientos { get; set; }

        [Display(Name = "Tipo de combustible")]
        [Required(ErrorMessage = "Campo requerido")]
        [MinLength(4, ErrorMessage = "El campo debe tener al menos una longitud de 4 caracteres")]
        [MaxLength(30, ErrorMessage = "El campo debe tener como máximo una longitud de 30 caracteres")]

        public string combustible { get; set; }

        [Display(Name = "Precio")]
        [Required(ErrorMessage = "Campo requerido")]
        [Range(0, 10000000.00, ErrorMessage = "El valor no puedo ser negativo")]
        public Nullable<decimal> precio { get; set; }

        [Display(Name = "Año")]
        [Required(ErrorMessage = "Campo requerido")]
        [Range(1700.00, 2019 , ErrorMessage = "Ingrese un a;o válido. Ej: 2002")]
        public string year_modelo { get; set; }

        [Display(Name = "Marca")]
        public Nullable<int> id_marca { get; set; }
    
        public virtual marca marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repuesto> repuestos { get; set; }
    }
}
