//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnotations_PartialViews.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class repuesto
    {
        public int id_rep { get; set; }

        [Display(Name = "Nombre del repuesto")]
        [Required(ErrorMessage = "Campo requerido")]
        [MinLength(4, ErrorMessage = "El campo debe tener al menos una longitud de 4 caracteres")]
        [MaxLength(30, ErrorMessage = "El campo debe tener como máximo una longitud de 30 caracteres")]
        public string nombre { get; set; }

        [Display(Name = "Precio")]
        [Required(ErrorMessage = "Campo requerido")]
        [Range(0, 10000000.00, ErrorMessage = "El valor no puedo ser negativo")]
        public Nullable<decimal> precio { get; set; }

        [Display(Name = "Descuento")]
        [Required(ErrorMessage = "Campo requerido")]
        [Range(0, 10000000.00, ErrorMessage = "El valor no puedo ser negativo")]
        public Nullable<int> descuento { get; set; }

        [Display(Name = "Modelo")]
        public Nullable<int> id_modelos { get; set; }
    
        public virtual modelo modelo { get; set; }
    }
}
